apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: job-pyspark-{{ macros.datetime.now().strftime("%Y-%m-%d-%H-%M-%S") }}
  namespace: airflow
spec:
  volumes:
    - name: ivy
      emptyDir: {}
  sparkConf:
    # spark.driver.extraJavaOptions: "-Dcom.amazonaws.services.s3.enableV4=true -Divy.cache.dir=/tmp -Divy.home=/tmp"
    # spark.executor.extraJavaOptions: "-Dcom.amazonaws.services.s3.enableV4=true -Divy.cache.dir=/tmp -Divy.home=/tmp"
    # extraJavaOptions: "-Dcom.amazonaws.services.s3.enableV4=true -Divy.cache.dir=/tmp -Divy.home=/tmp"    
    spark.jars.packages: "org.apache.hadoop:hadoop-aws:2.7.3,org.apache.spark:spark-avro_2.12:3.0.1"
    spark.kubernetes.allocation.batch.size: "10"
  hadoopConf:
    fs.s3a.aws.credentials.provider: com.amazonaws.auth.EnvironmentVariableCredentialsProvider
    fs.s3a.impl: org.apache.hadoop.fs.s3a.S3AFileSystem
    fs.s3a.endpoint: "s3.us-east-2.amazonaws.com"
    fs.s3a.path.style.access: “true”
    fs.s3a.connection.ssl.enabled: “true”    
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "597495568095.dkr.ecr.us-east-2.amazonaws.com/edc-m4-desafio:v3.0.0-aws"
  imagePullPolicy: Always
  mainApplicationFile: s3a://m4-597495568095/pyspark/enade_converte_parquet.py
  sparkVersion: "3.0.0"
  restartPolicy:
    type: Never
  driver:
    javaOptions: "-Dcom.amazonaws.services.s3.enableV4=true -Divy.cache.dir=/tmp -Divy.home=/tmp"
    envSecretKeyRefs:
      AWS_ACCESS_KEY_ID:
        name: aws-credentials
        key: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        name: aws-credentials
        key: aws_secret_access_key
    cores: 1
    coreLimit: "1200m"
    memory: "4g"
    labels:
      version: 3.0.0
    serviceAccount: airflow-worker
    volumeMounts:
      - name: ivy
        mountPath: /tmp
  executor:
    javaOptions: "-Dcom.amazonaws.services.s3.enableV4=true -Divy.cache.dir=/tmp -Divy.home=/tmp"
    envSecretKeyRefs:
      AWS_ACCESS_KEY_ID:
        name: aws-credentials
        key: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        name: aws-credentials
        key: aws_secret_access_key
    cores: 3
    instances: 3
    memory: "4g"
    labels:
      version: 3.0.0
    volumeMounts:
      - name: ivy
        mountPath: /tmp