# definição do secret
# para repositório privado do github
# GIT_SYNC_USERNAME e GIT_SYNC_PASSWORD 
# devem ser configurados nos parametros do 
# airflow em "myvalues.yaml"

apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
type: Opaque
data:
  GIT_SYNC_USERNAME: "usuario-base64"
  GIT_SYNC_PASSWORD: "token-base64"

